name: Factory Of Dreams
favicon: null
layout_spectrum: 0.23892
typography_spectrum: 0.93449
title: Factory Of Dreams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8d5d7'
    - '#fdce9c'
    - '#f19575'
    - '#b9c1cd'
    - '#9aacbc'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
