name: Factory Of Dreams
favicon: null
layout_spectrum: 0.74759
typography_spectrum: 0.10983
title: Factory Of Dreams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a3e1e1'
    - '#b99a78'
    - '#e2594a'
    - '#5c5c5c'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
